### ISSUE TITLE
install sphinx and migrate docstrings API from svn to GitHub

### ISSUE THREAD

**Issue by skrueger111** [madscatt/zazzie#134]
Once completed, help Susan get Sphinx installed on her machine so she can check her docstrings for the multi-component analysis module.

**Comment by madscatt** [comment]
Added directories and files for a Sphinx documentation system.  Ran make html and committed changes.

https://www.sphinx-doc.org/en/master/usage/quickstart.html

Currently using python2.7 version of sphinx-build etc.

To mirror (mostly) the file structure of documentation of zazmol the created html docs are in a folder named docs/.

Created a wiki page to begin the creation of our rules on documentation at the module level for SASSIE.  As SASSIE uses system integration tests rather than unit tests (which zazmol uses) the granularity has to be determined by the team.
